driver:
  name: vagrant

provisioner:
  name: chef_zero
  #chef_omnibus_install_options: '-c current'
  require_chef_omnibus: 12.12.15 # a chef release without yum built in

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: fedora-24
    run_list:
      - recipe[yum::dnf_yum_compat]

suites:
  - name: default
    run_list:
      - recipe[integration_test::default]
